# Generated by Django 3.2.7 on 2022-01-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollymovies_app', '0007_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('HR', 'Horror'), ('CM', 'Comedy'), ('TH', 'Thriller')], max_length=2, unique=True),
        ),
    ]
